### ISSUE TITLE
Issues with find_sym

### ISSUE THREAD

**Issue by garrison** [JuliaInterop/Clang.jl#131]
As of JuliaLang/julia@028d9dc, the `find_sym` function in `src/util.jl` is no longer type stable.  I was about to submit a pull request to remove the line `dl = C_NULL`, which I believe would fix it.

However, I got looking at the function and noticed a few things:
1. Shouldn't there be a `break` statement right after `found = true`?
2. What is this function used for, if anything?  It doesn't seem to be called anywhere in the entire julia package ecosystem.

**Comment by ihnorton** [comment]
Thanks, I'll remove it next time I work on this. It is currently unused.

> Shouldn't there be a break statement right after found = true?

yes

> What is this function used for, if anything? It doesn't seem to be called anywhere in the entire julia package ecosystem.

It was a helper function for some experiments a while back (pre-Cxx)... see #20.
