### ISSUE TITLE
C++ wrapping tutorial

### ISSUE THREAD

**Issue by TeroFrondelius** [JuliaInterop/Clang.jl#132]
Hi,
I have been couples of days learning (struggling) Clang.jl. I like the idea and I think this package could really boost scientific calculations, when people could be building on top of existing libraries. 

First really hard part was to get the package to building. I used this this type of trick (found somewhere else):

```
Pkg.checkout("Clang","master")
Pkg.build("Clang")
```

Secondly I tried to follow this https://github.com/ihnorton/Clang.jl#implementation
That really haven't helped so far, the ratio between code complexity and commenting is above my skills. 

Then I looked the tests and I thought I found something useful: https://github.com/ihnorton/Clang.jl/blob/master/test/test_classparents.jl
The problem is that it's not doing enough to work as a tutorial. 

Also the current documentation is not really helping, when the whole wrap_cpp is missing from there. 

If I could get this type of tutorial for c++, it really would help to the start

```
using Clang.wrap_c

context = wrap_c.init(; output_file="libjpeg.jl", header_library=x->"libjpeg", common_file="libjpeg_h.jl", clang_diagnostics=true)
context.options.wrap_structs = true
wrap_c.wrap_c_headers(context, ["/usr/include/jpeglib.h"])
```

**Comment by ihnorton** [comment]
check out github.com/Keno/Cxx.jl for the industrial-strength version.

**Comment by TeroFrondelius** [comment]
Thanks. I actually started by Cxx.jl. I just couldn't get Julia to compile with all those needed stuff. I gave up after three long nights. Maybe I will give another try.

**Comment by stemann** [comment]
Do Cxx provide an automatic wrapper generator?

Clang.jl fails to parse/translate/wrap the following C++ enum:
```c++
enum CpuFeatures {
    CPU_MMX             = 1
};
```
in https://github.com/opencv/opencv/blob/master/modules/core/include/opencv2/core/cvdef.h#L161

**Comment by Gnimuc** [comment]
Now you can use https://github.com/grasph/wrapit.
