### ISSUE TITLE
WARNING: Skipping VarArg Function CLCursor (Clang.cindex.FunctionDecl) 

### ISSUE THREAD

**Issue by mmacedoeu** [JuliaInterop/Clang.jl#146]
- First time trying to make binding for https://github.com/alanxz/rabbitmq-c 
- Installed Ubuntu packages librabbitmq and librabbitmq-dev
- Generated code with https://github.com/mmacedoeu/amqp.jl/blob/master/gen.jl
- Got following warning and the amqp_login is not generated:

```
WARNING: Skipping VarArg Function CLCursor (Clang.cindex.FunctionDecl) amqp_login(amqp_connection_state_t, const char *, int, int, int, amqp_sasl_method_enum, ...)
```

But it is mandatory to call this to use the library. Is there some workaround way to call amqp_login, even manually editing the generated file to include the missing function, does julialang support it ??https://github.com/alanxz/rabbitmq-c/blob/master/librabbitmq/amqp.h

**Comment by ihnorton** [comment]
Julia does not support vararg C functions.
https://github.com/JuliaLang/julia/issues/6661

**Comment by ihnorton** [comment]
You might be able to get away with using a `cdecl` ccall. I believe this
should match the expected ABI (args on-stack). YMMV, test thorougly, etc.

Looking at the docs for that function, if you do this you will need to
write different ccalls specific to the argument count and types for any
given authentication method. But that can (and should) be dispatched on the
Julia side first.
