### ISSUE TITLE
some characters are getting dropped at the beginning on generation

### ISSUE THREAD

**Issue by twadleigh** [JuliaInterop/Clang.jl#169]
I'm extracting some defines from a header file. I'm doing two different extractions from the same header for two different groups (with distinct prefixes). The files I'm producing each have a few characters missing from the front of the first `const`. Here are the first few lines from each of the generated files:

```
# Julia wrapper for header: C:\als\dvemp\04_Software\code\common\inc\netmsg.h
# Automatically generated using Clang.jl wrap_c, version 0.0.0

ETMSGID_RCP_STATUS = 2
const NETMSGID_RCP_CMD = 3
const NETMSGID_SPP_COMMAND = 5
const NETMSGID_SPP_STATUS_DVEONS = 6
const NETMSGID_SHARED_MEM_READY = 7
const NETMSGID_RADAR_DATA2 = 8
```

and

```
# Julia wrapper for header: C:\als\dvemp\04_Software\code\common\inc\netmsg.h
# Automatically generated using Clang.jl wrap_c, version 0.0.0

t NETMSGLEN_RCP_STATUS_HALS2 = 46
const NETMSGLEN_RCP_STATUS_HALS3 = 54
const NETMSGLEN_RCP_STATUS_DVEONS = 42
const NETMSGLEN_RCP_CMD = 18
const NETMSGLEN_RCP_CMD_DVEONS = 20
const NETMSGLEN_SPP_COMMAND = 120
```

It's a different number of characters getting dropped in each case.

I'm on windows. I had to hack up the `Makefile` to get `libwrapclang` to build under cygwin against the prebuilt LLVM for Win64 (3.8.1), but I think that was successful.

Any ideas?

**Comment by ihnorton** [comment]
That's really weird... I would guess that the output buffer is being corrupted, but I don't know how/why that would happen.

**Comment by twadleigh** [comment]
When/if I get back to this, I'm thinking I'll be using the clang generation at a lower level so that I can instead build dictionaries out of these `#define`s. Maybe in the process of doing that I might turn up the culprit.

**Comment by Gnimuc** [comment]
Clang.jl is now more friendly for building custom generators from scratch. If this happends again, feel free to reopen. :)
