### ISSUE TITLE
Move to JuliaInterop?

### ISSUE THREAD

**Issue by ViralBShah** [JuliaInterop/Clang.jl#170]
How about having this package be part of the Julia Interop union in JuliaInterop?

**Comment by tkelman** [comment]
@ihnorton bump?

**Comment by ihnorton** [comment]
What's the rationale? I'm not totally opposed, but I think JuliaInterop
makes less sense than most orgs. I guess there's some advertising benefit,
but not sure what else (I've given push access to just about everyone who
has ever made a PR here).

**Comment by ihnorton** [comment]
I guess moving would give me an excuse to rename to something much less
expansive.

**Comment by bjarthur** [comment]
the advertising benefit is huge

**Comment by ViralBShah** [comment]
Yep, mainly grouping and advertising that we have a great interoperability story and tools. But only if you think so. Not a necessity in any way.

**Comment by ihnorton** [comment]
Let's go ahead and do this. I think I need to be a temporary owner at JuliaInterop, or transfer it to an owner intermediate.

**Comment by ViralBShah** [comment]
@ihnorton Sent you an invite.

**Comment by ihnorton** [comment]
Done!

**Comment by ihnorton** [comment]
cc @Gnimuc FYI

**Comment by Gnimuc** [comment]
hi @ViralBShah, could you add me to JuliaInterop? I need the authority to maintain CI stuff. Also, I'm going to split the CEnum.jl from Clang.jl's source code and register it as a new package. CEnum.jl is originally written by Simon in #162, but it looks like he doesn't have time to maintain the package, so I guess we'd better to register it under JuliaInterop and people can work together.

**Comment by ViralBShah** [comment]
I have invited you as owner
