### ISSUE TITLE
Function and other signatures in comments

### ISSUE THREAD

**Issue by ihnorton** [JuliaInterop/Clang.jl#195]
For spot-checking and learning it would be nice to have an option to include original C signatures as comments (or docstrings?) next to the ccall and possibly other declarations.

**Comment by visr** [comment]
Somewhat related but less general, for GDAL.jl I'm using the GDAL Doxygen documentation XML to automatically create docstrings.
The docstrings are made [here](https://github.com/visr/GDAL.jl/blob/480f42b67a692e389d3064f1744d820a7ff194e9/gen/doc.jl) and added [here](https://github.com/visr/GDAL.jl/blob/480f42b67a692e389d3064f1744d820a7ff194e9/gen/rewriter.jl#L245-L248), resulting in docstrings [like this](https://github.com/visr/GDAL.jl/blob/480f42b67a692e389d3064f1744d820a7ff194e9/src/gdal_h.jl#L314-L326).
