### ISSUE TITLE
Potential wrong alignments and sizes of structs with C unions

### ISSUE THREAD

**Issue by cdsousa** [JuliaInterop/Clang.jl#238]
There is an issue in the way Clang.jl wraps C unions by just picking the largest alternative.
The problem occurs when a union is inside a struct and when such union contains an alternative which, while not being the largest one, is composed of elements with greater word sizes than all the other alternatives or other elements of the struct.

See this example:

```c
struct struct_with_union
{
  float x;
  union {
    double y;
    float z[10];
  } foo;
} struct_with_union;
```
Clang will wrap that in Julia by something like (names not completely right):
```julia
struct ANONYMOUS___
  z::NTuple{10, Float32}
end
struct struct_with_union
  x::Float32
  foo::ANONYMOUS___
end
```

The size of `struct_with_union` in Julia will be 44 bytes: 4 for `x` plus 10*4 for `z` (the largest in the union). 

However, the actual size of the struct in C is 48 bytes: 10*4 for `z` plus 4 for `x`, plus padding of 4 between `x` and `z`.
That padding comes, AFAIK, to the fact that the largest word possible in the struct is the 8-byte double from the `y` alternative and thus all the elements get aligned to the 8-byte boundaries.

**Comment by cdsousa** [comment]
BTW, a practical problem was reported in  https://github.com/JuliaGPU/CUDAdrv.jl/issues/165 .

**Comment by Gnimuc** [comment]
Currently, the support for nested/anomyous unions or unusual padded structs is quite nasty, see #224, #233, etc. For now, you need to use some workarounds as I mentioned [here](https://github.com/JuliaInterop/Clang.jl/issues/233#issuecomment-523260973). 

There was a plan to completely drop the current implementation of `wrap_c` and reimplement it using [`fieldoffset`](https://github.com/JuliaInterop/Clang.jl/issues/224#issuecomment-466880356) to auto-generate code like [this](https://github.com/JuliaMultimedia/CSFML.jl/blob/812f21224d683f4119b02c456dda47d4d0a4a471/src/Window/window_common.jl#L272-L314).

**Comment by Gnimuc** [comment]
hi @cdsousa, could you give #278 a test? I don't know where to start with CUDAdrv.

**Comment by maleadt** [comment]
CUDAdrv is deprecated, that functionality is now part of CUDA.jl. The wrapper generators are here: https://github.com/JuliaGPU/CUDA.jl/tree/master/res/wrap, and the relevant code is at https://github.com/JuliaGPU/CUDA.jl/blob/6ec21d343d04f9118018e6e04c2dba23eaf90523/src/texture.jl#L224-L238 and https://github.com/JuliaGPU/CUDA.jl/blob/6ec21d343d04f9118018e6e04c2dba23eaf90523/lib/cudadrv/libcuda_common.jl#L938-L950. But I can have a look later when I get to the LLVM.jl changes.

**Comment by Gnimuc** [comment]
Thanks for the links, I'm going to take a look this weekend.
