### ISSUE TITLE
Header file references not found 

### ISSUE THREAD

**Issue by jd-lara** [JuliaInterop/Clang.jl#242]
This issue is similar to #240 for Sundials v5.0.0. The wrap file is in here https://github.com/Energy-MAC/Sundials.jl/blob/jd/Sundialsv5/src/wrap_sundials.jl

When we run the wrap code even if it find the the `stdio.h` header it still fails to find the definitions. 

```Julia
julia --color=yes wrap_sundials.jl
/Code/Sundials.jl/deps/usr/include/sundials/sundials_fconfig.h:1:1: error: expected identifier or '('
/Code/Sundials.jl/deps/usr/include/arkode/arkode_butcher.h:61:47: error: unknown type name 'FILE'
/Code/Sundials.jl/deps/usr/include/arkode/arkode_butcher.h:64:59: error: unknown type name 'FILE'
/Code/Sundials.jl/deps/usr/include/arkode/arkode_butcher.h:68:54: error: unknown type name 'FILE'
/Code/Sundials.jl/deps/usr/include/arkode/arkode_butcher.h:61:47: error: unknown type name 'FILE'
/Code/Sundials.jl/deps/usr/include/arkode/arkode_butcher.h:64:59: error: unknown type name 'FILE'
/Code/Sundials.jl/deps/usr/include/arkode/arkode_butcher.h:68:54: error: unknown type name 'FILE'
/Code/Sundials.jl/deps/usr/include/arkode/arkode_butcher.h:61:47: error: unknown type name 'FILE'
/Code/Sundials.jl/deps/usr/include/arkode/arkode_butcher.h:64:59: error: unknown type name 'FILE'
/Code/Sundials.jl/deps/usr/include/arkode/arkode_butcher.h:68:54: error: unknown type name 'FILE'
[ Info: wrapping header: 
/Code/Sundials.jl/deps/usr/include/nvector/nvector_manyvector.h ...
┌ Warning: not wrapping CLCursor (CLLastPreprocessing) stdio.h
└ @ Clang ~/.julia/packages/Clang/CiPzM/src/wrap_c.jl:443
┌ Warning: not wrapping CLCursor (CLLastPreprocessing) sundials/sundials_nvector.h
└ @ Clang ~/.julia/packages/Clang/CiPzM/src/wrap_c.jl:443
```
And in the latter functions calls, it also fails to find other header files that are defined and included in the init function for instance: 

```Julia
[ Info: wrapping header: 
/Code/Sundials.jl/deps/usr/include/nvector/nvector_serial.h ...
┌ Warning: not wrapping CLCursor (CLLastPreprocessing) stdio.h
└ @ Clang ~/.julia/packages/Clang/CiPzM/src/wrap_c.jl:443
┌ Warning: not wrapping CLCursor (CLLastPreprocessing) sundials/sundials_nvector.h
```

And also here: 

```Julia
[ Info: wrapping header: 
/Code/Sundials.jl/deps/usr/include/sundials/sundials_math.h ...
┌ Warning: not wrapping CLCursor (CLLastPreprocessing) math.h
└ @ Clang ~/.julia/packages/Clang/CiPzM/src/wrap_c.jl:443
┌ Warning: not wrapping CLCursor (CLLastPreprocessing) sundials/sundials_types.h
└ @ Clang ~/.julia/packages/Clang/CiPzM/src/wrap_c.jl:443
┌ Warning: not wrapping CLCursor (CLMacroInstantiation) SUNDIALS_USE_GENERIC_MATH
└ @ Clang ~/.julia/packages/Clang/CiPzM/src/wrap_c.jl:443
┌ Warning: not wrapping CLCursor (CLMacroInstantiation) SUNDIALS_USE_GENERIC_MATH
└ @ Clang ~/.julia/packages/Clang/CiPzM/src/wrap_c.jl:443
┌ Warning: not wrapping CLCursor (CLMacroInstantiation) SUNDIALS_USE_GENERIC_MATH
└ @ Clang ~/.julia/packages/Clang/CiPzM/src/wrap_c.jl:443
┌ Warning: not wrapping CLCursor (CLMacroInstantiation) SUNDIALS_USE_GENERIC_MATH
└ @ Clang ~/.julia/packages/Clang/CiPzM/src/wrap_c.jl:443
┌ Warning: not wrapping CLCursor (CLMacroInstantiation) SUNDIALS_EXPORT
└ @ Clang ~/.julia/packages/Clang/CiPzM/src/wrap_c.jl:443
┌ Warning: not wrapping CLCursor (CLMacroInstantiation) SUNDIALS_EXPORT
└ @ Clang ~/.julia/packages/Clang/CiPzM/src/wrap_c.jl:443
```

The header files are in the SundialsBuilder repo https://github.com/Energy-MAC/SundialsBuilder/tree/jd/sundialsv5 

If you run build with this version of Sundials.jl https://github.com/Energy-MAC/Sundials.jl.git#jd/Sundialsv5 then the headers we are using can be downloaded. 

The original wrap_sundials file is still in the repo as well for reference in https://github.com/Energy-MAC/Sundials.jl/blob/jd/Sundialsv5/src/wrap_sundials_old.jl

**Comment by Gnimuc** [comment]
> When we run the wrap code even if it find the the `stdio.h` header it still fails to find the definitions.

I don't work on Linux. Currently, `find_std_headers` only finds std-headers for macOS. I can reproduce this issue on a Windows machine as well. Which linux distribution are you working on? Are there any std-headers in `/include`?

> And in the latter functions calls, it also fails to find other header files that are defined and included in the init function for instance:

I guess you misunderstood those warning messages. 

```
[ Info: wrapping header: 
/Code/Sundials.jl/deps/usr/include/nvector/nvector_serial.h ...
┌ Warning: not wrapping CLCursor (CLLastPreprocessing) stdio.h
└ @ Clang ~/.julia/packages/Clang/CiPzM/src/wrap_c.jl:443
```

This message means there is a `#include<stdio.h>`(or a "CLLastPreprocessing cursor" in the language of Clang AST) in the header code, and this is neither a function prototype nor a type, so we do nothing here.

**Comment by jd-lara** [comment]
I am doing this on a Mac not linux. That' why I use `find_std_headers` 

Thanks for the clarification on the warning, I thought that Clang would need to re-parse the headers.

**Comment by Gnimuc** [comment]
Are you working on Catalina? I don't know why Apple changes the include path so often, but it could be under this dir: `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk`

**Comment by jd-lara** [comment]
I also tried adding that path manually, the whole path. I used both versions Catalina and Mojave

**Comment by Gnimuc** [comment]
@jd-lara I tried it again on Mojave with [this script](https://gist.github.com/Gnimuc/e0879bd2ad1e56997abb25696ab77381) and now I only get this compile error:
```
[ Info: Generating .jl wrappers for Sundials in /Users/gnimuc/.julia/dev/Sundials/src/wrapped_api...
/Users/gnimuc/.julia/dev/Sundials/deps/usr/include/sundials/sundials_fconfig.h:1:1: error: expected identifier or '('
```
But this sundials_fconfig.h file is definitely not written in standard C/C++, so the compiler should complain.

**Comment by jd-lara** [comment]
Yeah, that's a weird header for fortran it seems. Thanks for the help.
