### ISSUE TITLE
Unexported API

### ISSUE THREAD

**Issue by inkydragon** [JuliaInterop/Clang.jl#243]
Three questions:

## Q1: Unexported API in `libclang.dll`

Check [clang/libclang.exports](https://github.com/llvm-mirror/clang/blob/master/tools/libclang/libclang.exports), there is no `clang_CompileCommand_getNumMappedSources`

https://github.com/JuliaInterop/Clang.jl/blob/7f9da947fe7238b2cdd4c332e6a85b6a6c1a7d0f/gen/libclang_api.jl#L100-L102

And I double check this export list by using [DLL Export Viewer](https://www.nirsoft.net/utils/dll_export_viewer.html), There are 360 functions in `libclang.dll` as the same as `libclang.exports`.

ref:
- [⚙ D32351 [Tooling][libclang] Remove unused CompilationDatabase::MappedSources](https://reviews.llvm.org/D32351)

----

## Q2: Some deprecated functions

+ `clang_CompileCommand_getNumMappedSources`
+ `clang_CompileCommand_getMappedSourcePath`
+ `clang_CompileCommand_getMappedSourceContent`

Also those three functions are 
> Left here for backward compatibility. No mapped sources exists in the C++ backend anymore.

they just return `0` or `Null`. 
We may add some deprecation warnings to them.

ref:
- [clang/CXCompilationDatabase.cpp at master · llvm-mirror/clang](https://github.com/llvm-mirror/clang/blob/master/tools/libclang/CXCompilationDatabase.cpp#L145-L167)
- [gen/main.go at master · go-clang/gen](https://github.com/go-clang/gen/blob/master/cmd/go-clang-gen/main.go#L148)

----

## Q3: Unexported API in `libclang_api.jl`

+ [clang/Index.h#L6130 & L6134](https://github.com/llvm-mirror/clang/blob/master/include/clang-c/Index.h#L6123-L6138)
    + `clang_findIncludesInFileWithBlock` 
    + `clang_findReferencesInFileWithBlock`
+ [clang/Index.h#L4207](https://github.com/llvm-mirror/clang/blob/master/include/clang-c/Index.h#L4188-L4210)
    + `clang_visitChildrenWithBlock`

All those three functions are listed in `libclang.exports` and exist in `libclang.dll`, but not export in `libclang_api.jl`.

**Comment by Gnimuc** [comment]
Q1, Q2: currently Clang.jl uses libclang 6.0.1, could you check it again that those deprecated functions were actually deprecated at 6.0.1? 

Q3: that's because `__has_feature` was not defined when generating those bindings. This implies we might need to pass some C++1x flags.

**Comment by inkydragon** [comment]
> could you check it again that those deprecated functions were actually deprecated at 6.0.1?

- [clang/CXCompilationDatabase.cpp at release_60 · llvm-mirror/clang](https://github.com/llvm-mirror/clang/blob/release_60/tools/libclang/CXCompilationDatabase.cpp#L145-L167)
- Clang 6.0.0 Release Notes: [clang/ReleaseNotes.rst at release_60 · llvm-mirror/clang](https://github.com/llvm-mirror/clang/blob/release_60/docs/ReleaseNotes.rst)

I do checked `libclang.dll` which located in `Clang.jl\deps\usr\bin`.

**Comment by Gnimuc** [comment]
`wrap_c` generates C-bindings only based on header files, so the API for those functions will be generated as long as they're not removed from libclang's header files.
