### ISSUE TITLE
Wrong result with v0.10.0 

### ISSUE THREAD

**Issue by HerrHao** [JuliaInterop/Clang.jl#256]
I used to use Clang@0.9.1, today i update to v0.10.0, find that this Pkg wrongly translate size_t to Cint, and can't recognize some local structrues, while it works good at version 0.9.1.

**Comment by Gnimuc** [comment]
Are you on macOS?

**Comment by HerrHao** [comment]
No, win10 64

**Comment by Gnimuc** [comment]
Please share more diagnostic info or an MWE. :)

**Comment by Gnimuc** [comment]
This problem usually happens when Clang.jl fails to find those system headers.

**Comment by Gnimuc** [comment]
Aha, [found it](https://github.com/JuliaInterop/Clang.jl/blob/11bc8757073a5a7a32464b34460922829760ba75/src/Clang.jl#L76). I'm going to push a fix later on.

**Comment by HerrHao** [comment]
thanks a lot
