### ISSUE TITLE
Support bool type (with implementation defined size)

### ISSUE THREAD

**Issue by femtomc** [JuliaInterop/Clang.jl#275]
Boolean types https://en.cppreference.com/w/cpp/language/types have implementation defined size. I think this poses a problem for `Clang.jl`:

```julia
const MLIR_C_INCLUDE = joinpath(@__DIR__, "..", "julia/usr/include/mlir-c") |> normpath
const MLIR_C_HEADERS = [joinpath(MLIR_C_INCLUDE, header) for header in readdir(MLIR_C_INCLUDE) if endswith(header, ".h")]
wc = init(; headers = MLIR_C_HEADERS,
          output_file = joinpath(@__DIR__, "lib/libmlir_api.jl"),
          common_file = joinpath(@__DIR__, "lib/libmlir_common.jl"),
          clang_includes = vcat(LIBCLANG_INCLUDE, CLANG_INCLUDE),
          clang_args = ["-I", joinpath(LIBCLANG_INCLUDE, ".."),
                        "-I", joinpath(MLIR_C_INCLUDE, "..")],
          header_wrapped = (root, current) -> root == current,
          header_library = x -> "libmlir",
          clang_diagnostics = false,
         )
run(wc)
```
displays
```julia
/home/mccoy/mlir_dev/julia/usr/include/mlir-c/Support.h:98:15: error: unknown type name 'bool'
/home/mccoy/mlir_dev/julia/usr/include/mlir-c/Support.h:103:15: error: unknown type name 'bool'
/home/mccoy/mlir_dev/julia/usr/include/mlir-c/../mlir-c/Support.h:98:15: error: unknown type name 'bool'
/home/mccoy/mlir_dev/julia/usr/include/mlir-c/../mlir-c/Support.h:103:15: error: unknown type name 'bool'
```
for C
```c
/// Checks if the given logical result represents a success.
inline static bool mlirLogicalResultIsSuccess(MlirLogicalResult res) {
  return res.value != 0;
}

/// Checks if the given logical result represents a failure.
inline static bool mlirLogicalResultIsFailure(MlirLogicalResult res) {
  return res.value == 0;
}
```

Edit: this is possibility not an issue - but I just wanted to check.

**Comment by Gnimuc** [comment]
Please add a link to the header that you're trying to wrap, so I can debug it on my machine.

The error complains about a common C error, [`error-unknown-type-name-bool`](https://stackoverflow.com/questions/8133074/error-unknown-type-name-bool), so a proper fix could be to add some compiler flags or do an ad-hoc fix to the source code. 

Please double-check the build instructions of mlir-c, especially those compiler flags, and make sure they are correctly passed to `clang_args ` .

**Comment by femtomc** [comment]
Yes - it's the `MLIR` C API headers: https://github.com/llvm/llvm-project/tree/main/mlir/include/mlir-c

**Comment by Gnimuc** [comment]
OK, I'm going to take a look at it this weekend.

**Comment by Gnimuc** [comment]
Hi @femtomc, adding the missing `#include <stdbool.h>` to `Support.h` will fix the problem.

**Comment by Gnimuc** [comment]
OK, I just submitted the change to the upstream: https://reviews.llvm.org/D93588

**Comment by Gnimuc** [comment]
Should be fixed now. Feel free to reopen if the issue persists.
