### ISSUE TITLE
Argument and type name equivalent

### ISSUE THREAD

**Issue by vchuravy** [JuliaInterop/Clang.jl#279]
```
void flux_stat_watcher_get_rstat (flux_watcher_t *w,
                                  struct stat *stat, struct stat *prev)
```

Produces:

```
function flux_stat_watcher_get_rstat(w, stat, prev)
    ccall((:flux_stat_watcher_get_rstat, libflux_core), Cvoid, (Ptr{flux_watcher_t}, Ptr{stat}, Ptr{stat}), w, stat, prev)
end
```

Which fails with, because the type name `stat` is shadowed by the local variable name `stat`

x-ref: https://github.com/flux-framework/FluxRM.jl/pull/6

**Comment by Gnimuc** [comment]
Thanks for reporting this! I'm currently reworking the whole generator in #278 and do need test cases like this one.
