### ISSUE TITLE
LoadError: LibraryProduct(...) is not satisfied, cannot generate deps.jl!

### ISSUE THREAD

**Issue by alejandrovgonzalez** [JuliaInterop/Clang.jl#283]
Hello!

Ive been trying to install Clang.jl in my Windows machine and I always run with the following issue when doing `add Clang`:
![Capture](https://user-images.githubusercontent.com/24530176/112665471-c56b9280-8e63-11eb-9463-0fd26793593d.PNG)

Do you have any idea on how to fix this?

Thank you.

**Comment by alejandrovgonzalez** [comment]
Update: Seems to be a problem with Julia 1.6; in Julia 5.4 all works fine.

**Comment by Gnimuc** [comment]
I'm reworking the whole package in PR #278 and have introduced some breaking changes. If you're starting from scratch, then it's better to use PR #278, the API is much simpler. Unfortunately, I didn't write any docs, but I guess you could treat [this script](https://github.com/JuliaInterop/Clang.jl/blob/bb8a31dc5af94f6e2c76a70f582792dea144e568/gen/generator.jl) as an example.

You can find more examples here: https://github.com/Gnimuc/GeneratorScripts.

**Comment by alejandrovgonzalez** [comment]
Thanks for your answer @Gnimuc, I will now close the issue.
