### ISSUE TITLE
Julia v1.6?

### ISSUE THREAD

**Issue by dojt** [JuliaInterop/Clang.jl#285]
Is it possible to drop the < 1.6 requirement on the Julia version?

https://github.com/JuliaInterop/Clang.jl/blob/5b3055efcb12bb973a61dbca31188517a9affbdf/Project.toml#L15

**Comment by dojt** [comment]
... on my system, all tests pass, but the following warning occurs several times:
```
┌ Warning: default libname: ":libxxx" are being used, did you forget to specify `context.libname`?                                                                                                          
└ @ Clang ~/tmp/Clang/src/wrap_c.jl:65
```

**Comment by Gnimuc** [comment]
> Is it possible to drop the < 1.6 requirement on the Julia version?

Yep, just bump julia and Clang_jll versions. The reason why I did not upgrade the package is that I'm currently reworking on the package in https://github.com/JuliaInterop/Clang.jl/pull/278 and going to submit PRs to all of the downstream repos that use Clang.jl as a wrapper generator.

**Comment by sa-** [comment]
Clang.jl fails to build with 1.6 on my local, but 1.5 works fine

**Comment by Gnimuc** [comment]
@sa- Failed with `> dev Clang`?

**Comment by Gnimuc** [comment]
I'm sorry for the inconvenience. Is it a good idea to tag a new version of the old Clang.jl for Julia 1.6? Please vote up with the thumbs-up emoji if you think so.

**Comment by sa-** [comment]
It works with `dev Clang`! :D

**Comment by Gnimuc** [comment]
I just release a new version (v0.13.0) of the old generator for Julia 1.6 and for those authors who have no willing to update the script at the moment.
