### ISSUE TITLE
LoadError: sanity check failed.

### ISSUE THREAD

**Issue by Wimmerer** [JuliaInterop/Clang.jl#290]
`sanity check failed. [REASON]: use the same name clingo_symbol_type for struct CLCursor (Clang.CLEnumDecl) clingo_symbol_type at /home/will/.julia/artifacts/1e309d9f5e2efe88a12072f45b428baae9bc8b20/include/clingo.h:306:6 and function CLCursor (Clang.CLFunctionDecl) clingo_symbol_type(clingo_symbol_t) at /home/will/.julia/artifacts/1e309d9f5e2efe88a12072f45b428baae9bc8b20/include/clingo.h:421:48. The C code use the same name for structs and functions, which is not a good code-style, please fix it in the upstream.`

Is there any way around this? In many cases it's not feasible to fix something in the upstream like this. This is on master.

**Comment by Gnimuc** [comment]
Looks like this has already been fixed in the upstream: https://github.com/potassco/clingo/commit/7c5b26c9d17d5e1785df25b23e63196e44af5ac4 😉

**Comment by Wimmerer** [comment]
Perfect, thanks for your help :)
