### ISSUE TITLE
Release an updated Clang_jll for LLVM 12

### ISSUE THREAD

**Issue by femtomc** [JuliaInterop/Clang.jl#291]
@Gnimuc This is unfortunately currently preventing me from working on an MLIR-based project. I'm not sure what is required to do this -- if you enumerate what is required, I can try and tackle it.

**Comment by Gnimuc** [comment]
I'm still reworking the new generator. Do you wanna use the old generator with LLVM12 or the new generator?

**Comment by Gnimuc** [comment]
Please leave a link to your repo. I can help to upgrade the script.

**Comment by femtomc** [comment]
https://github.com/vchuravy/MLIR.jl/blob/mrb/brutus_codesign/res/wrap.jl This is the script.

**Comment by femtomc** [comment]
(On master, it's: https://github.com/vchuravy/MLIR.jl/blob/main/create_bindings.jl)

**Comment by Gnimuc** [comment]
Are you sure it's LLVM 12? We don't have those LLVM 12 binaries in the Ygg yet.

**Comment by femtomc** [comment]
Yes, sorry -- I should have been more clear. I'm working with LLVM 12 on a build of Julia:
<img width="440" alt="image" src="https://user-images.githubusercontent.com/34410036/115866720-0f667a80-a408-11eb-9410-8a112d96c4b5.png">

I'm trying to generate wrappers for MLIR using this build -- but I'm not sure if I can get around using `Clang_jll` -- which is restricted to 11. That means I can't actually use it, because precompilation throws:

<img width="681" alt="image" src="https://user-images.githubusercontent.com/34410036/115866809-3755de00-a408-11eb-921b-38c336916003.png">

which makes sense, it's looking for LLVM 11.

**Comment by Gnimuc** [comment]
One workaround is to generate bindings using Clang.jl with an official Julia-1.6.

**Comment by femtomc** [comment]
Fair -- I'll try that now.

**Comment by Gnimuc** [comment]
Sorry, it should be 1.5 with Clang.jl-0.12, 1.6 with Clang.jl-master. I'm about to submit a PR to MLIR.jl for upgrading that generator script to be compatible with Clang.jl-master.

**Comment by femtomc** [comment]
@Gnimuc Dope! Also, I just wrapped the headers directly with a normal build of Julia. Seems to be working.

**Comment by Gnimuc** [comment]
UPDATE:
pending-upstream: https://github.com/JuliaPackaging/Yggdrasil/pull/2906
