### ISSUE TITLE
Upgrade generator scripts for downstream packages

### ISSUE THREAD

**Issue by Gnimuc** [JuliaInterop/Clang.jl#299]
We should upgrade all of the packages in the list below before releasing v0.14.0:

- [x] https://github.com/SciML/Sundials.jl
- [x] https://github.com/JuliaGeo/GDAL.jl
- [x] https://github.com/JuliaGeo/LibGEOS.jl
- [x] https://github.com/JuliaGeo/Proj4.jl
- [x] https://github.com/JuliaIO/VideoIO.jl
- [ ] https://github.com/JuliaGPU/CUDA.jl
- [x] https://github.com/JuliaGPU/AMDGPU.jl
- [x] https://github.com/JuliaParallel/UCX.jl
- [ ] https://github.com/JuliaGL/XCB.jl
- [x] https://github.com/JuliaIO/PNGFiles.jl
- [ ] https://github.com/JuliaMolSim/Libxc.jl
- [ ] https://github.com/JuliaTagBot/ArrowGlib.jl
- [ ] https://github.com/jump-dev/Cbc.jl
- [x] https://github.com/jump-dev/Clp.jl
- [ ] https://github.com/jump-dev/Xpress.jl
- [ ] https://github.com/jump-dev/GLPK.jl
- [ ] https://github.com/jump-dev/Gurobi.jl
- [ ] https://github.com/jump-dev/CPLEX.jl
- [x] https://github.com/jump-dev/HiGHS.jl
- [ ] https://github.com/FluxML/Torch.jl
- [ ] https://github.com/RelationalAI-oss/SQLParser.jl
- [x] https://github.com/CEED/libCEED
- [x] https://github.com/wookay/H3.jl
- [ ] https://github.com/samuelpowell/Spinnaker.jl
- [ ] https://github.com/rveltz/LSODA.jl
- [x] https://github.com/twadleigh/OpenEXR.jl
- [ ] https://github.com/laborg/HidApi.jl
- [ ] https://github.com/zyth0s/SciAlgs.jl
- [ ] https://github.com/jerryzhenleicai/LevelDB.jl
- [ ] https://github.com/wsphillips/LibUMP.jl
- [ ] https://github.com/TEOS-10/GibbsSeaWater.jl
- [ ] https://github.com/sisl/CUDD.jl
- [ ] https://github.com/MasFlam/XCBased.jl
- [ ] https://github.com/sa-/Polars.jl
- [ ] https://github.com/iuliancioarca/LibIIO.jl
- [x] https://github.com/IanButterworth/Darknet.jl
- [ ] https://github.com/arhik/RtMidi.jl
- [ ] https://github.com/dss-extensions/OpenDSSDirect.jl
- [ ] https://github.com/JaneliaSciComp/ImarisWriter.jl
- [ ] https://github.com/GMLC-TDC/HELICS.jl
- [x] https://github.com/hildebrandmw/OneDNN.jl
- [x] https://github.com/PhilipVinc/MetalCore.jl

**Comment by Gnimuc** [comment]
42, not great, not terrible.

**Comment by ankitkumarakt746** [comment]
Hi Gnimuc, 
I couldn't understand what kind of upgrade to the packages are you refering to.

**Comment by Gnimuc** [comment]
Rewriting those scripts(e.g. [this one](https://github.com/JuliaGeo/GDAL.jl/blob/master/gen/wrap.jl#L187-L202)) to use Clang.jl#master's latest `Clang.Generators` API: https://github.com/JuliaInterop/Clang.jl#quick-start.

**Comment by melonedo** [comment]
H3.jll is already updated

**Comment by Gnimuc** [comment]
@melonedo thanks for the hard work! When upgrading those downstream packages, it would be great if all of the pain points can be ameliorated at the Clang.jl's side. For example, instead of doing hacks like 
https://github.com/JuliaWeb/LibCURL.jl/pull/105/files#diff-010a0ce3257c161674e34d0844cbaf23d451042222bdff2794ca3836e12cf478R17-R31, we can provide an option for generating enums as constants in the generator.

**Comment by odow** [comment]
Very nice. Don't let the `jump-dev` repos block the release. We can take care to update them in the future. They aren't urgent.

**Comment by melonedo** [comment]
I also updated generator scripts for VideoIO https://github.com/JuliaIO/VideoIO.jl/pull/333.
