### ISSUE TITLE
"$" expression outside quote around...

### ISSUE THREAD

**Issue by colinxs** [JuliaInterop/Clang.jl#311]
I'm attempting to wrap `<sys/mman.h>` which runs successfully but generators the following line:

```julia
const __ptr_t = $(Expr(:incomplete, "incomplete: premature end of input"))
```

resulting in the error:
```
LoadError: syntax: "$" expression outside quote around /home/colinxs/workspace/crypto/obs/gen/mman.jl:313
```

The corresponding c code is in `<sys/cdefs.h>`:
```c
/* This is not a typedef so `const __ptr_t' does the right thing.  */
#define __ptr_t void *
```

I can blacklist it for now, since it's not used directly in the generated code, but figured I'd file an issue to put it on the radar.

**Comment by Gnimuc** [comment]
Thanks for reporting this!
