### ISSUE TITLE
Integer sizes and signals lost

### ISSUE THREAD

**Issue by cdsousa** [JuliaInterop/Clang.jl#313]
With a default configuration this
```c
struct A
{
    int16_t x;
    int16_t y;
    uint32_t z;
};

void f(int16_t x);
```
gets translate to this
```julia
struct A
    x::Cint
    y::Cint
    z::Cint
end

function f(x)
    @ccall libclang.f(x::Cint)::Cvoid
end
```

Looking into https://github.com/JuliaInterop/Clang.jl/blob/master/src/generator/definitions.jl I'd suppose that these integers would be well translated. (I couldn't find any option related to this too.)

**Comment by Gnimuc** [comment]
`Cint` is a flag that means clang failed to parse your source code. When parsing code with Clang.jl, one needs to treat it as a real clang compiler, so all of those compiler flags should be passed correctly. 

`int16_t` and `uint32_t ` are defined in `stdint.h`, so you should add `#include <stdint.h>` to your code.

Maybe I should add this info to FAQ.
