### ISSUE TITLE
Update to Julia v1.7

### ISSUE THREAD

**Issue by ranocha** [JuliaInterop/Clang.jl#314]
Currently, Clang.jl requires Clang_jll v11, which is not compatible with libLLVM_jll v12 used in Julia v1.7 (v1.7.0-beta3.0, currently). For example,
```julia
(@v1.7) pkg> add Clang#master
     Cloning git-repo `https://github.com/JuliaInterop/Clang.jl.git`
    Updating git-repo `https://github.com/JuliaInterop/Clang.jl.git`
    Updating registry at `~/.julia/registries/General.toml`
   Resolving package versions...
ERROR: Unsatisfiable requirements detected for package libLLVM_jll [8f36deef]:
 libLLVM_jll [8f36deef] log:
 ├─possible versions are: 12.0.0 or uninstalled
 └─found to have no compatible versions left with Clang_jll [0ee61d77]
   └─Clang_jll [0ee61d77] log:
     ├─possible versions are: 9.0.1-12.0.1 or uninstalled
     └─restricted to versions 11.0.1-11.0 by Clang [40e3b903], leaving only versions 11.0.1
       └─Clang [40e3b903] log:
         ├─possible versions are: 0.14.0 or uninstalled
         └─Clang [40e3b903] is fixed to version 0.14.0

julia> versioninfo()
Julia Version 1.7.0-beta3.0
Commit e76c9dad42 (2021-07-07 08:12 UTC)
```

- When will Clang.jl be updated such that it can be used in Julia v1.7?
- Related: Are there any plans when v0.14 of Clang.jl using the new generator API will be released?

The reason I'm asking is that we used [CBindingGen.jl](https://github.com/analytech-solutions/CBindingGen.jl) before, but that package is archived and will not be updated to Julia v1.7. Thus, we need to switch either to Clang.jl or [CBinding.jl](https://github.com/analytech-solutions/CBinding.jl).

**Comment by Gnimuc** [comment]
Try this branch: https://github.com/JuliaInterop/Clang.jl/tree/julia-1.7

**Comment by Gnimuc** [comment]
> When will Clang.jl be updated such that it can be used in Julia v1.7?

The master branch will default to Julia-v1.7 when Julia v1.7 is officially released.

> Related: Are there any plans when v0.14 of Clang.jl using the new generator API will be released?

I'm not sure. I'm actually waiting for feedback/feature requests from users. As v0.14 is a breaking release, I would like to make it API-stable from now on, so the API of current master can be considered stable. 

There are still a couple of issues that need to be fixed, you could take a look at https://github.com/JuliaInterop/Clang.jl/milestone/1.

**Comment by ranocha** [comment]
> Try this branch: https://github.com/JuliaInterop/Clang.jl/tree/julia-1.7
>
> > When will Clang.jl be updated such that it can be used in Julia v1.7?
> 
> The master branch will default to Julia-v1.7 when Julia v1.7 is officially released.

Thanks, that works fine for me :+1:

**Comment by ranocha** [comment]
> > Related: Are there any plans when v0.14 of Clang.jl using the new generator API will be released?
> 
> I'm not sure. I'm actually waiting for feedback/feature requests from users. As v0.14 is a breaking release, I would like to make it API-stable from now on, so the API of current master can be considered stable.

Thanks for this offer. Is it okay for you to open new issues or do you prefer another way of communicating?

**Comment by ranocha** [comment]
From a first look, the new generator interface is quite nice - good job :+1: However, there is very little documentation, which makes it sometimes hard to use or adapt...

**Comment by Gnimuc** [comment]
@melonedo is currently working on the documentation for the upcoming v0.14 features. If you have some instant questions, feel free to DM me on Slack(#clang channel) or post the question on https://github.com/JuliaInterop/Clang.jl/discussions. 🙂

**Comment by ranocha** [comment]
Great, thanks! Feel free to close this issue (or keep it open until Julia v1.7 is released to make it easier to find for others running into the same question).
