### ISSUE TITLE
Wrong order of generated structs for generation of structs containing anonymous unions

### ISSUE THREAD

**Issue by martinkosch** [JuliaInterop/Clang.jl#325]
Hi everyone, 
thank you for the amazing package so far!

I think I encountered a small (but annoying) bug in the current master branch: the generation of structs containing anonymous unions prints the corresponding Julia union wrapper struct after the original struct definition. 

In my case, the C struct

```C  
typedef struct {
      enum NodeIdType id_type;
      union {
          UInt32     numeric;
          Guid       guid;
      } id;
  } NodeId;
```
results in the generated code

```julia
mutable struct NodeId
    id_type::NodeIdType
    id::__JL_Ctag_295
    NodeId() = new()
end
...
struct __JL_Ctag_295
    data::NTuple{16, UInt8}
end
```
leading to 
```
ERROR: LoadError: LoadError: UndefVarError: __JL_Ctag_295 not defined
```
If I am not missing something, the problem can be solved by changing the order of the generated structs.

**Comment by Gnimuc** [comment]
This can be fixed by storing the indices of those nested records in the `option` Dict and then add a pass to print them right after the prologue printer pass.

**Comment by martinkosch** [comment]
Printing the nested records right after the prologue does not solve the problem though if the nested records themselves depend on other structs that are defined after the prologue.

**Comment by Gnimuc** [comment]
You're right. A better way is to add the indices of those inner nested structs to the nested struct. In this way, the order will be sorted automatically in the toposort pass.
