### ISSUE TITLE
Can not handle pointer to anonymous struct

### ISSUE THREAD

**Issue by melonedo** [JuliaInterop/Clang.jl#326]
```c
typedef struct {
    int a, b;
} B, *C;
```
Clang.jl can not distinguish B from C.

**Comment by melonedo** [comment]
It seems that it has been hard-wired to be directly `typedef some_type another_type`:
https://github.com/JuliaInterop/Clang.jl/blob/50670a80c38bb73e0772debf16fe68040a4654e9/src/generator/codegen.jl#L257-L262

Changing L259 to more flexible form
```julia
ty = getTypedefDeclUnderlyingType(node.cursor)
typedefee = translate(tojulia(ty), options)
```
seems to solve the problem.

**Comment by Onyinye91-ctrl** [comment]
@Gnimuc Can i make the edit?

**Comment by melonedo** [comment]
I already submitted the change at #324, though it will take a while before this PR gets merged.
