### ISSUE TITLE
Void type is not shown correctly

### ISSUE THREAD

**Issue by melonedo** [JuliaInterop/Clang.jl#327]
Currently, `void` is shown as `CLFirstType`, which is not very informative, this is because Clang includes First* and Last* as auxiliary enums that indicate ranges after main enum section, while the more informative one come first, changing  the type mapping to prefer names that come first rather than last may solve this.

**Comment by Gnimuc** [comment]
A possible fix would be to filter out those marker enum names in https://github.com/JuliaInterop/Clang.jl/blob/master/src/cltypes.jl.
