### ISSUE TITLE
Can not wrap macro `#define __cdecl`

### ISSUE THREAD

**Issue by melonedo** [JuliaInterop/Clang.jl#328]
This occured when I am wrapping CUDA(`$(CUDA_full_jll.artifact_dir)/cuda/targets/x86_64-linux/include/crt/host_defines.h` for x86_64-linux-gnu target). The c code 
```c
#define __cdecl
```
Triggers assertion error, because `__cdecl` is a keyword, while https://github.com/JuliaInterop/Clang.jl/blob/50670a80c38bb73e0772debf16fe68040a4654e9/src/generator/macro.jl#L317 asserts the expression is not empty.

`@add_def __cdecl` is possible fix is this header is in system headers, but sometimes this may not be very handy.

**Comment by Gnimuc** [comment]
you could ignore it by adding it to this list:

https://github.com/JuliaInterop/Clang.jl/blob/50670a80c38bb73e0772debf16fe68040a4654e9/src/generator/macro.jl#L199
