### ISSUE TITLE
release 0.14?

### ISSUE THREAD

**Issue by matbesancon** [JuliaInterop/Clang.jl#349]
It's been a while and some packages using master, should Clang.jl have a 0.14 release?

**Comment by Gnimuc** [comment]
I'm waiting for the Julia 1.7 official release. If you'd like to use Clang.jl with Julia 1.7-rc, please switch to https://github.com/JuliaInterop/Clang.jl/pull/347

**Comment by matbesancon** [comment]
but wouldn't it make sense to have a 0.14 release working with julia 1.6 which will also be the LTS, and then add a new breaking change working only with 1.7+

**Comment by Gnimuc** [comment]
That's also a good idea. We can have a 0.15 release for Julia 1.7.

**Comment by matbesancon** [comment]
I just reran master on SCIP to update to the new version of the C library, worked like a charm, definitely worth it releasing now IMO :)

**Comment by Gnimuc** [comment]
Done!
