### ISSUE TITLE
Error when generating from a certain syntax structure

### ISSUE THREAD

**Issue by KristofferC** [JuliaInterop/Clang.jl#355]
I have some code that structurally looks like:

```c
typedef struct s {
} s;

int (*s_f(const struct s* n))(struct s*);
```

When trying to generate this I hit https://github.com/JuliaInterop/Clang.jl/issues/354 because:

```julia
cursor = CLCursor (Clang.CLFunctionDecl) s_f(const struct s *)
args = Clang.CLCursor[CLCursor (Clang.CLParmDecl) , CLCursor (Clang.CLParmDecl) n]
types = Clang.CLType[CLType (Clang.CLPointer) , CLType (Clang.CLInvalid) ]
```

in https://github.com/JuliaInterop/Clang.jl/blob/2c9230dc28a7d6d3bb33025b8c99a302f7ce5170/src/generator/system_deps.jl#L11-L12

**Comment by Gnimuc** [comment]
@KristofferC  I can't parse this C code `int (*s_f(const struct s* n))(struct s*);`

**Comment by melonedo** [comment]
> @KristofferC I can't parse this C code `int (*s_f(const struct s* n))(struct s*);`
> 
> https://cdecl.org also gives a syntax error.

You could remove the parameter name `n`, then it gives:
> declare s_f as function (pointer to const struct s) returning pointer to function (pointer to struct s) returning int
