### ISSUE TITLE
Prefixed string literals

### ISSUE THREAD

**Issue by KristofferC** [JuliaInterop/Clang.jl#357]
Prefixed string literals will right now emit the prefix as is:

```c
#define S L"string"
```

emits

```jl
const S = L"string"
```

leading to an error when the file is included since no `L`-string macro is defined. 

Perhaps the prefix can just be removed, alt a no-op `L`-string macro can be defined since the `cconvert` from the type signatures should take care of it (albeit with a copy for `String` -> `Cwstring`).

**Comment by Gnimuc** [comment]
The hard part is that libclang doesn't expose enough APIs for identifying the `L`-string macros.
