### ISSUE TITLE
what is pure definition macro?

### ISSUE THREAD

**Issue by johnnychen94** [JuliaInterop/Clang.jl#374]
```julia
using TOML
using Clang.Generators

option_str = """
[codegen.macro]
ignore_pure_definition = false
"""
options = TOML.parse(option_str)
header_str = """
#define VERSION 0.0.1
"""
header = "a.h"
write(header, header_str)
ctx = create_context(header, get_default_args(), options)
build!(ctx)
```

I was expecting this generates

```julia
const VERSION = "0.0.1"
```

but it seems Clang would unconditionally skip it:

```julia
# Skipping MacroDefinition: VERSION 0.0.1
```

Is there a way to tell Clang generators to bypass the dependency analysis and still generate `const VERSION = "0.0.1"`?

**Comment by Gnimuc** [comment]
`0.0.1` is either a valid number or a string. Although it's quite obvious to us that `VERSION` is a semantic version number, it's not trivial to teach the generator to understand this concept. Is `2022.1.31` a version number?

**Comment by Gnimuc** [comment]
But if you write `#define VERSION "0.0.1"`, then there is no need to let the generator know extra concepts because in this case, the value can be assigned to the string "0.0.1" regardless of the underlying concept we gave.

**Comment by Gnimuc** [comment]
> what is pure definition macro?

I don't know whether there is an official name or not. These kinda macros are like:

```
#define LIB_EXPORT
```
