### ISSUE TITLE
C_LONG_LONG and C_INT64_T represented as Clong

### ISSUE THREAD

**Issue by amontoison** [JuliaInterop/Clang.jl#399]
`C_LONG_LONG` and `C_INT64_T` should be represented as `Clonglong` and `Int64` because `Clong == Int32` on Windows platforms.

**Comment by Gnimuc** [comment]
Any context?

**Comment by amontoison** [comment]
I used the default one that is in the documentation.

**Comment by Gnimuc** [comment]
Where is this `C_LONG_LONG` stuff?

**Comment by amontoison** [comment]
Sorry @Gnimuc, the issue was between and the chair and the screen.
The package that I wanted to interface forgot to update header files, they just changed types in f90 files...
