### ISSUE TITLE
`__restrict not defined` Error

### ISSUE THREAD

**Issue by JBlaschke** [JuliaInterop/Clang.jl#400]
While trying to generate C-bindings for Hwloc_jll I get the following error:

```julia
ERROR: LoadError: UndefVarError: __restrict not defined
```

Looking at the generated code, the error is being thrown by:
```julia
const __hwloc_restrict = __restrict
```
Should this be ignored by the code generator (it looks like it might be getting confused by `restrict`, `__restrict`,  and `__restrict__`)?

**Comment by Gnimuc** [comment]
Basically, if you don't need that symbol(`__hwloc_restrict`), you could workaround this by adding it in the [`output_ignorelist`](https://github.com/JuliaInterop/Clang.jl/blob/d95ff2d562561a5b8dda9ad568e95c317a3efd52/gen/generator.toml#L49).

> Should this be ignored by the code generator (it looks like it might be getting confused by `restrict`, `__restrict`, and `__restrict__`)?

Yes. I'm currently expanding [this list](https://github.com/JuliaInterop/Clang.jl/blob/master/src/generator/macro.jl#L223) case by case.

**Comment by Gnimuc** [comment]
Fixed by https://github.com/JuliaInterop/Clang.jl/commit/e3a60ee91b10211ce017c0e39b11ac3eae82f7ca .

**Comment by JBlaschke** [comment]
Brilliant ! Thanks @Gnimuc
