### ISSUE TITLE
Resource failed

### ISSUE THREAD

**Issue by Blumenkranz** [JuliaInterop/Clang.jl#457]
It seems that the resource `fbb170fa64a06b66dd9a16aaa21bf12848042d9a` of `GCCBootstrap-aarch64-apple-darwin20.v11.0.0-iains.x86_64-linux-musl.unpacked` in `Artifact.toml` has been failed.

**Comment by Gnimuc** [comment]
indeed, `Artifact.toml` hasn't been updated for a while, but the old resource should not fail.
