### ISSUE TITLE
Function with no arguments (sometimes?) recognized as varargs function

### ISSUE THREAD

**Issue by kmsquire** [JuliaInterop/Clang.jl#87]
I've been exploring AVBin as an alternative to libav.  One thing I've noticed is that some functions with no arguments there are recognized as varargs functions and skipped.

I'm a little confused why, as I did not see the same thing when wrapping libav (but maybe there are fewer no-arg functions).

I can get around this by disabling that check in wrap_c.jl, but there's probably a better fix.  Not sure when I'll have time to look into it.

For testing: https://github.com/kmsquire/AV.jl/blob/master/util/wrap_avbin.jl (and AVbin installed, of course).

**Comment by rollingthunder** [comment]
If I had come across this issue a little earlier, that would have saved me some debugging work.

The code I wrote to handle this case is part of my pull request: dfdfbc0

In case you don't like my quick fix, some kind of handling of this would still be nice to have.

**Comment by Gnimuc** [comment]
Already fixed in dfdfbc0, so closed this.
